// DATA FILE - All game data including countries, capitals, flags, etc.

const GAME_DATA = {
    // COUNTRIES BY DIFFICULTY
    countries: {
        easy: [
            { name: 'China', flag: '🇨🇳', capital: 'Pequim', abbr: ['China'] },
            { name: 'Rússia', flag: '🇷🇺', capital: 'Moscou', abbr: ['Rusia', 'Rússia'] },
            { name: 'Brasil', flag: '🇧🇷', capital: 'Brasília', abbr: ['Brasil'] },
            { name: 'Estados Unidos', flag: '🇺🇸', capital: 'Washington DC', abbr: ['EUA', 'USA', 'Estados Unidos'] },
            { name: 'Índia', flag: '🇮🇳', capital: 'Nova Délhi', abbr: ['India', 'Índia'] },
            { name: 'Japão', flag: '🇯🇵', capital: 'Tóquio', abbr: ['Japao', 'Japão'] },
            { name: 'Alemanha', flag: '🇩🇪', capital: 'Berlim', abbr: ['Alemanha'] },
            { name: 'Reino Unido', flag: '🇬🇧', capital: 'Londres', abbr: ['Reino Unido', 'UK', 'Inglaterra', 'Gran Bretanha', 'GB'] },
            { name: 'França', flag: '🇫🇷', capital: 'Paris', abbr: ['Franca', 'França'] },
            { name: 'Itália', flag: '🇮🇹', capital: 'Roma', abbr: ['Italia', 'Itália'] },
            { name: 'Canadá', flag: '🇨🇦', capital: 'Ottawa', abbr: ['Canada', 'Canadá'] },
            { name: 'México', flag: '🇲🇽', capital: 'Cidade do México', abbr: ['Mexico', 'México'] },
            { name: 'Austrália', flag: '🇦🇺', capital: 'Camberra', abbr: ['Australia', 'Austrália'] },
            { name: 'Coreia do Sul', flag: '🇰🇷', capital: 'Seul', abbr: ['Coreia do Sul', 'Coreia', 'Corea'] },
            { name: 'Espanha', flag: '🇪🇸', capital: 'Madrid', abbr: ['Espanha'] },
            { name: 'Argentina', flag: '🇦🇷', capital: 'Buenos Aires', abbr: ['Argentina'] },
            { name: 'Turquia', flag: '🇹🇷', capital: 'Ancara', abbr: ['Turquia', 'Turquia'] },
            { name: 'Tailândia', flag: '🇹🇭', capital: 'Bancoque', abbr: ['Tailandia', 'Tailândia'] },
            { name: 'Indonésia', flag: '🇮🇩', capital: 'Jacarta', abbr: ['Indonesia', 'Indonésia'] },
            { name: 'Filipinas', flag: '🇵🇭', capital: 'Manila', abbr: ['Filipinas'] },
            { name: 'Paquistão', flag: '🇵🇰', capital: 'Islamabade', abbr: ['Paquistao', 'Paquistão'] },
            { name: 'Bangladesh', flag: '🇧🇩', capital: 'Daca', abbr: ['Bangladesh'] },
            { name: 'Vietnã', flag: '🇻🇳', capital: 'Hanói', abbr: ['Vietna', 'Vietnã'] },
            { name: 'Marrocos', flag: '🇲🇦', capital: 'Rabate', abbr: ['Marrocos'] },
            { name: 'Egito', flag: '🇪🇬', capital: 'Cairo', abbr: ['Egito'] },
            { name: 'África do Sul', flag: '🇿🇦', capital: 'Pretória', abbr: ['Africa do Sul', 'South Africa', 'RSA'] },
            { name: 'Nigéria', flag: '🇳🇬', capital: 'Abuja', abbr: ['Nigeria', 'Nigéria'] },
            { name: 'Quênia', flag: '🇰🇪', capital: 'Nairóbi', abbr: ['Quenia', 'Quênia'] },
            { name: 'Chile', flag: '🇨🇱', capital: 'Santiago', abbr: ['Chile'] },
            { name: 'Peru', flag: '🇵🇪', capital: 'Lima', abbr: ['Peru'] },
            { name: 'Colômbia', flag: '🇨🇴', capital: 'Bogotá', abbr: ['Colombia', 'Colômbia'] },
            { name: 'Venezuela', flag: '🇻🇪', capital: 'Caracas', abbr: ['Venezuela'] },
            { name: 'Grécia', flag: '🇬🇷', capital: 'Atenas', abbr: ['Grecia', 'Grécia'] },
            { name: 'Portugal', flag: '🇵🇹', capital: 'Lisboa', abbr: ['Portugal'] },
            { name: 'Suécia', flag: '🇸🇪', capital: 'Estocolmo', abbr: ['Suecia', 'Suécia'] },
            { name: 'Noruega', flag: '🇳🇴', capital: 'Oslo', abbr: ['Noruega'] },
            { name: 'Dinamarca', flag: '🇩🇰', capital: 'Copenhague', abbr: ['Dinamarca'] },
            { name: 'Finlândia', flag: '🇫🇮', capital: 'Helsinque', abbr: ['Finlandia', 'Finlândia'] },
            { name: 'Polônia', flag: '🇵🇱', capital: 'Varsóvia', abbr: ['Polonia', 'Polônia'] },
            { name: 'Holanda', flag: '🇳🇱', capital: 'Amsterdã', abbr: ['Holanda', 'Paises Baixos', 'Países Baixos', 'Netherlands'] },
            { name: 'Bélgica', flag: '🇧🇪', capital: 'Bruxelas', abbr: ['Belgica', 'Bélgica'] },
            { name: 'Áustria', flag: '🇦🇹', capital: 'Viena', abbr: ['Austria', 'Áustria'] },
            { name: 'Suíça', flag: '🇨🇭', capital: 'Berna', abbr: ['Suica', 'Suíça'] },
            { name: 'Irlanda', flag: '🇮🇪', capital: 'Dublin', abbr: ['Irlanda'] },
            { name: 'Israel', flag: '🇮🇱', capital: 'Jerusalém', abbr: ['Israel'] },
            { name: 'Arábia Saudita', flag: '🇸🇦', capital: 'Riade', abbr: ['Arabia Saudita', 'Arábia Saudita', 'Saudi Arabia'] },
            { name: 'Irã', flag: '🇮🇷', capital: 'Teerã', abbr: ['Ira', 'Irã', 'Iran'] },
            { name: 'Iraque', flag: '🇮🇶', capital: 'Bagdá', abbr: ['Iraque', 'Iraq'] },
            { name: 'Síria', flag: '🇸🇾', capital: 'Damasco', abbr: ['Siria', 'Síria'] },
            { name: 'Líbano', flag: '🇱🇧', capital: 'Beirute', abbr: ['Libano', 'Líbano'] },
            { name: 'Jordânia', flag: '🇯🇴', capital: 'Amã', abbr: ['Jordania', 'Jordânia'] },
            { name: 'Emirados Árabes Unidos', flag: '🇦🇪', capital: 'Abu Dhabi', abbr: ['EAU', 'Emirados Arabes', 'Emirados Árabes Unidos', 'UAE'] },
        ],
        medium: [
            { name: 'Paraguai', flag: '🇵🇾', capital: 'Assunção', abbr: ['Paraguai'] },
            { name: 'Panamá', flag: '🇵🇦', capital: 'Cidade do Panamá', abbr: ['Panama', 'Panamá'] },
            { name: 'Camboja', flag: '🇰🇭', capital: 'Phnom Penh', abbr: ['Camboja'] },
            { name: 'Laos', flag: '🇱🇦', capital: 'Vientiana', abbr: ['Laos'] },
            { name: 'Mianmar', flag: '🇲🇲', capital: 'Naipidã', abbr: ['Mianmar', 'Burma'] },
            { name: 'Malásia', flag: '🇲🇾', capital: 'Kuala Lumpur', abbr: ['Malasia', 'Malásia'] },
            { name: 'Singapura', flag: '🇸🇬', capital: 'Singapura', abbr: ['Singapura'] },
            { name: 'Nepal', flag: '🇳🇵', capital: 'Catmandu', abbr: ['Nepal'] },
            { name: 'Sri Lanka', flag: '🇱🇰', capital: 'Colombo', abbr: ['Sri Lanka'] },
            { name: 'Mongólia', flag: '🇲🇳', capital: 'Ulan Bator', abbr: ['Mongolia', 'Mongólia'] },
            { name: 'Cazaquistão', flag: '🇰🇿', capital: 'Nur-Sultã', abbr: ['Cazaquistao', 'Cazaquistão'] },
            { name: 'Uzbequistão', flag: '🇺🇿', capital: 'Tashkent', abbr: ['Uzbequistao', 'Uzbequistão'] },
            { name: 'Turcomenistão', flag: '🇹🇲', capital: 'Ashkhabad', abbr: ['Turcomenistao', 'Turcomenistão'] },
            { name: 'Tajiquistão', flag: '🇹🇯', capital: 'Dushanbe', abbr: ['Tajiquistao', 'Tajiquistão'] },
            { name: 'Afeganistão', flag: '🇦🇫', capital: 'Cabul', abbr: ['Afeganistao', 'Afeganistão'] },
            { name: 'Geórgia', flag: '🇬🇪', capital: 'Tbilisi', abbr: ['Georgia', 'Geórgia'] },
            { name: 'Armênia', flag: '🇦🇲', capital: 'Erevan', abbr: ['Armenia', 'Armênia'] },
            { name: 'Azerbaijão', flag: '🇦🇿', capital: 'Baku', abbr: ['Azerbaijao', 'Azerbaijão'] },
            { name: 'Ucrânia', flag: '🇺🇦', capital: 'Kiev', abbr: ['Ukrania', 'Ucrânia'] },
            { name: 'Bielorrússia', flag: '🇧🇾', capital: 'Minsk', abbr: ['Bielorrussia', 'Bielorrússia', 'Belarus'] },
            { name: 'Moldávia', flag: '🇲🇩', capital: 'Chisinau', abbr: ['Moldavia', 'Moldávia'] },
            { name: 'Romênia', flag: '🇷🇴', capital: 'Bucareste', abbr: ['Romania', 'Romênia'] },
            { name: 'Bulgária', flag: '🇧🇬', capital: 'Sofia', abbr: ['Bulgaria', 'Bulgária'] },
            { name: 'Servia', flag: '🇷🇸', capital: 'Belgrado', abbr: ['Serbia', 'Servia'] },
            { name: 'Croácia', flag: '🇭🇷', capital: 'Zagreb', abbr: ['Croacia', 'Croácia'] },
            { name: 'Eslovênia', flag: '🇸🇮', capital: 'Liubliana', abbr: ['Eslovenia', 'Eslovênia'] },
            { name: 'Hungria', flag: '🇭🇺', capital: 'Budapeste', abbr: ['Hungria', 'Hungria'] },
            { name: 'República Checa', flag: '🇨🇿', capital: 'Praga', abbr: ['Republica Checa', 'República Checa', 'Tchequia', 'Chequia'] },
            { name: 'Eslováquia', flag: '🇸🇰', capital: 'Bratislava', abbr: ['Eslovaquia', 'Eslováquia'] },
            { name: 'Lituânia', flag: '🇱🇹', capital: 'Vilnius', abbr: ['Lituania', 'Lituânia'] },
            { name: 'Letônia', flag: '🇱🇻', capital: 'Riga', abbr: ['Letonia', 'Letônia'] },
            { name: 'Estônia', flag: '🇪🇪', capital: 'Talinn', abbr: ['Estonia', 'Estônia'] },
            { name: 'Guatemala', flag: '🇬🇹', capital: 'Cidade da Guatemala', abbr: ['Guatemala'] },
            { name: 'Honduras', flag: '🇭🇳', capital: 'Tegucigalpa', abbr: ['Honduras'] },
            { name: 'El Salvador', flag: '🇸🇻', capital: 'San Salvador', abbr: ['El Salvador'] },
            { name: 'Nicarágua', flag: '🇳🇮', capital: 'Manágua', abbr: ['Nicaragua', 'Nicarágua'] },
            { name: 'Costa Rica', flag: '🇨🇷', capital: 'San José', abbr: ['Costa Rica'] },
            { name: 'Belize', flag: '🇧🇿', capital: 'Belmopã', abbr: ['Belize'] },
            { name: 'Jamaica', flag: '🇯🇲', capital: 'Kingston', abbr: ['Jamaica'] },
            { name: 'Trinidad e Tobago', flag: '🇹🇹', capital: 'Porto de Espanha', abbr: ['Trinidad e Tobago', 'Trinidad and Tobago'] },
            { name: 'Bahamas', flag: '🇧🇸', capital: 'Nassau', abbr: ['Bahamas'] },
            { name: 'Cuba', flag: '🇨🇺', capital: 'Havana', abbr: ['Cuba'] },
            { name: 'República Dominicana', flag: '🇩🇴', capital: 'Santo Domingo', abbr: ['Republica Dominicana', 'República Dominicana', 'Dominica'] },
            { name: 'Haiti', flag: '🇭🇹', capital: 'Porto Príncipe', abbr: ['Haiti'] },
            { name: 'Uruguai', flag: '🇺🇾', capital: 'Montevidéu', abbr: ['Uruguai'] },
            { name: 'Bolívia', flag: '🇧🇴', capital: 'Sucre', abbr: ['Bolivia', 'Bolívia'] },
            { name: 'Equador', flag: '🇪🇨', capital: 'Quito', abbr: ['Equador'] },
            { name: 'Surinã', flag: '🇸🇷', capital: 'Paramaribo', abbr: ['Surinam', 'Surinã'] },
            { name: 'Guiana', flag: '🇬🇾', capital: 'Georgetown', abbr: ['Guiana'] },
        ],
        hard: [
            { name: 'Macedônia do Norte', flag: '🇲🇰', capital: 'Skopje', abbr: ['Macedonia do Norte', 'Macedônia do Norte', 'Macedonia', 'ARYM'] },
            { name: 'Bósnia e Herzegovina', flag: '🇧🇦', capital: 'Sarajevo', abbr: ['Bosnia e Herzegovina', 'Bósnia e Herzegovina', 'Bosnia', 'BiH'] },
            { name: 'Kosovo', flag: '🇽🇰', capital: 'Pristina', abbr: ['Kosovo'] },
            { name: 'Montenegro', flag: '🇲🇪', capital: 'Podgorica', abbr: ['Montenegro'] },
            { name: 'Albânia', flag: '🇦🇱', capital: 'Tirana', abbr: ['Albania', 'Albânia'] },
            { name: 'Luxemburgo', flag: '🇱🇺', capital: 'Luxemburgo', abbr: ['Luxemburgo'] },
            { name: 'Malta', flag: '🇲🇹', capital: 'Valleta', abbr: ['Malta'] },
            { name: 'Ciprè', flag: '🇨🇾', capital: 'Nicósia', abbr: ['Cipre', 'Ciprè', 'Cyprus'] },
            { name: 'Islândia', flag: '🇮🇸', capital: 'Reiquiavique', abbr: ['Islandia', 'Islândia'] },
            { name: 'Brunei', flag: '🇧🇳', capital: 'Bandar Seri Begawan', abbr: ['Brunei'] },
            { name: 'Timor-Leste', flag: '🇹🇱', capital: 'Díli', abbr: ['Timor-Leste', 'Timor Leste'] },
            { name: 'Papua Nova Guiné', flag: '🇵🇬', capital: 'Port Moresby', abbr: ['Papua Nova Guine', 'Papua Nova Guiné', 'Papua New Guinea'] },
            { name: 'Fiji', flag: '🇫🇯', capital: 'Suva', abbr: ['Fiji'] },
            { name: 'Vanuatu', flag: '🇻🇺', capital: 'Port Vila', abbr: ['Vanuatu'] },
            { name: 'Samoa', flag: '🇼🇸', capital: 'Apia', abbr: ['Samoa'] },
            { name: 'Kiribati', flag: '🇰🇮', capital: 'Taraua', abbr: ['Kiribati'] },
            { name: 'Tonga', flag: '🇹🇴', capital: 'Nuku\'alofa', abbr: ['Tonga'] },
            { name: 'Nauru', flag: '🇳🇷', capital: 'Yaren', abbr: ['Nauru'] },
            { name: 'Palau', flag: '🇵🇼', capital: 'Ngerulmud', abbr: ['Palau'] },
            { name: 'Maurício', flag: '🇲🇺', capital: 'Porto Luís', abbr: ['Mauricio', 'Maurício', 'Mauritius'] },
            { name: 'Seicheles', flag: '🇸🇨', capital: 'Vitória', abbr: ['Seicheles', 'Seychelles'] },
            { name: 'Comores', flag: '🇰🇲', capital: 'Moroni', abbr: ['Comores'] },
            { name: 'Mauretânia', flag: '🇲🇷', capital: 'Nuakchote', abbr: ['Mauritania', 'Mauretânia'] },
            { name: 'Benin', flag: '🇧🇯', capital: 'Porto Novo', abbr: ['Benin'] },
            { name: 'Togo', flag: '🇹🇬', capital: 'Lomé', abbr: ['Togo'] },
            { name: 'Gana', flag: '🇬🇭', capital: 'Acra', abbr: ['Gana', 'Ghana'] },
            { name: 'Libéria', flag: '🇱🇷', capital: 'Monróvia', abbr: ['Liberia', 'Libéria'] },
            { name: 'Serra Leoa', flag: '🇸🇱', capital: 'Freetown', abbr: ['Serra Leoa', 'Sierra Leone'] },
            { name: 'Guiné', flag: '🇬🇳', capital: 'Conacri', abbr: ['Guine', 'Guiné', 'Guinea'] },
            { name: 'Guiné-Bissau', flag: '🇬🇼', capital: 'Bissau', abbr: ['Guine-Bissau', 'Guiné-Bissau', 'Guinea-Bissau'] },
            { name: 'Senegal', flag: '🇸🇳', capital: 'Dacar', abbr: ['Senegal'] },
            { name: 'Mali', flag: '🇲🇱', capital: 'Bamaco', abbr: ['Mali'] },
            { name: 'Burkina Fasso', flag: '🇧🇫', capital: 'Uagadugu', abbr: ['Burkina Faso', 'Burkina Fasso'] },
            { name: 'Níger', flag: '🇳🇪', capital: 'Niamei', abbr: ['Niger', 'Níger'] },
            { name: 'Chade', flag: '🇹🇩', capital: 'Ndjamena', abbr: ['Chade', 'Chad'] },
            { name: 'Sudan', flag: '🇸🇩', capital: 'Cartum', abbr: ['Sudan'] },
            { name: 'Sudão do Sul', flag: '🇸🇸', capital: 'Juba', abbr: ['Sudao do Sul', 'Sudão do Sul', 'South Sudan'] },
            { name: 'Etiópia', flag: '🇪🇹', capital: 'Adis Abeba', abbr: ['Etiopia', 'Etiópia'] },
            { name: 'Eritreia', flag: '🇪🇷', capital: 'Asmara', abbr: ['Eritreia'] },
            { name: 'Djibouti', flag: '🇩🇯', capital: 'Djibouti', abbr: ['Djibouti'] },
            { name: 'Somália', flag: '🇸🇴', capital: 'Mogadíscio', abbr: ['Somalia', 'Somália'] },
            { name: 'Uganda', flag: '🇺🇬', capital: 'Kampala', abbr: ['Uganda'] },
            { name: 'Tanzânia', flag: '🇹🇿', capital: 'Dar es Salaam', abbr: ['Tanzania', 'Tanzânia'] },
            { name: 'Moçambique', flag: '🇲🇿', capital: 'Maputo', abbr: ['Mocambique', 'Moçambique'] },
            { name: 'Malavi', flag: '🇲🇼', capital: 'Lilongwe', abbr: ['Malawi', 'Malavi'] },
            { name: 'Zâmbia', flag: '🇿🇲', capital: 'Lusaca', abbr: ['Zambia', 'Zâmbia'] },
            { name: 'Zimbábue', flag: '🇿🇼', capital: 'Harare', abbr: ['Zimbabwe', 'Zimbábue'] },
            { name: 'Botswana', flag: '🇧🇼', capital: 'Gaborone', abbr: ['Botswana'] },
            { name: 'Lesoto', flag: '🇱🇸', capital: 'Maseru', abbr: ['Lesoto', 'Lesotho'] },
            { name: 'Eswatini', flag: '🇸🇿', capital: 'Mbabane', abbr: ['Eswatini', 'Swaziland'] },
        ],
        veryhard: [
            { name: 'Ilhas Marshall', flag: '🇲🇭', capital: 'Majuro', abbr: ['Ilhas Marshall', 'Marshall Islands'] },
            { name: 'San Marino', flag: '🇸🇲', capital: 'San Marino', abbr: ['San Marino'] },
            { name: 'Dominica', flag: '🇩🇲', capital: 'Roseau', abbr: ['Dominica'] },
            { name: 'Micronésia', flag: '🇫🇲', capital: 'Paliquer', abbr: ['Micronesia', 'Micronésia'] },
            { name: 'Maldivas', flag: '🇲🇻', capital: 'Malé', abbr: ['Maldivas', 'Maldives'] },
            { name: 'Barbados', flag: '🇧🇧', capital: 'Bridgetown', abbr: ['Barbados'] },
            { name: 'Granada', flag: '🇬🇩', capital: 'Saint George\'s', abbr: ['Granada', 'Grenada'] },
            { name: 'Santa Lúcia', flag: '🇱🇨', capital: 'Castries', abbr: ['Santa Lucia', 'Santa Lúcia'] },
            { name: 'São Vicente e Granadinas', flag: '🇻🇨', capital: 'Kingstown', abbr: ['Sao Vicente e Granadinas', 'São Vicente e Granadinas'] },
            { name: 'Antígua e Barbuda', flag: '🇦🇬', capital: 'Saint John\'s', abbr: ['Antigua e Barbuda', 'Antígua e Barbuda', 'Antigua'] },
            { name: 'Bermuda', flag: '🇧🇲', capital: 'Hamilton', abbr: ['Bermuda'] },
            { name: 'Aruba', flag: '🇦🇼', capital: 'Oranjestad', abbr: ['Aruba'] },
            { name: 'Curaçao', flag: '🇨🇼', capital: 'Willemstad', abbr: ['Curacao', 'Curaçao'] },
            { name: 'Sint Maarten', flag: '🇸🇽', capital: 'Philipsburg', abbr: ['Sint Maarten'] },
            { name: 'Niue', flag: '🇳🇺', capital: 'Alofi', abbr: ['Niue'] },
            { name: 'Ilhas Cayman', flag: '🇰🇾', capital: 'George Town', abbr: ['Ilhas Cayman', 'Cayman Islands'] },
            { name: 'Turcos e Caicos', flag: '🇹🇨', capital: 'Cockburn Town', abbr: ['Turcos e Caicos', 'Turks and Caicos'] },
            { name: 'Saint Kitts e Névis', flag: '🇰🇳', capital: 'Basseterre', abbr: ['Saint Kitts e Nevis', 'Saint Kitts e Névis'] },
            { name: 'Anguila', flag: '🇦🇮', capital: 'The Valley', abbr: ['Anguila', 'Anguilla'] },
            { name: 'Montserrat', flag: '🇲🇸', capital: 'Plymouth', abbr: ['Montserrat'] },
            { name: 'Ilhas Virgens Britânicas', flag: '🇻🇬', capital: 'Road Town', abbr: ['Ilhas Virgens Britanicas', 'Ilhas Virgens Britânicas'] },
            { name: 'Ilhas Virgens Americanas', flag: '🇻🇮', capital: 'Charlotte Amalie', abbr: ['Ilhas Virgens Americanas', 'US Virgin Islands'] },
            { name: 'Porto Rico', flag: '🇵🇷', capital: 'San Juan', abbr: ['Porto Rico', 'Puerto Rico'] },
            { name: 'Guam', flag: '🇬🇺', capital: 'Hagatna', abbr: ['Guam'] },
            { name: 'Polinésia Francesa', flag: '🇵🇫', capital: 'Papeete', abbr: ['Polinesia Francesa', 'Polinésia Francesa'] },
            { name: 'Samoa Americana', flag: '🇦🇸', capital: 'Pago Pago', abbr: ['Samoa Americana', 'American Samoa'] },
            { name: 'Ilhas Aland', flag: '🇦🇽', capital: 'Mariehamn', abbr: ['Ilhas Aland', 'Aland Islands'] },
            { name: 'Groenlândia', flag: '🇬🇱', capital: 'Nuuk', abbr: ['Gronlandia', 'Groenlândia', 'Greenland'] },
            { name: 'Faroé', flag: '🇫🇴', capital: 'Tórshavn', abbr: ['Faroe', 'Faroé'] },
            { name: 'Isle of Man', flag: '🇮🇲', capital: 'Douglas', abbr: ['Isle of Man'] },
            { name: 'Guernesey', flag: '🇬🇬', capital: 'Saint Peter Port', abbr: ['Guernesey', 'Guernsey'] },
            { name: 'Jersey', flag: '🇯🇪', capital: 'Saint Helier', abbr: ['Jersey'] },
            { name: 'Andorra', flag: '🇦🇩', capital: 'Andorra la Vella', abbr: ['Andorra'] },
            { name: 'Liechtenstein', flag: '🇱🇮', capital: 'Vaduz', abbr: ['Liechtenstein'] },
            { name: 'Mônaco', flag: '🇲🇨', capital: 'Mônaco', abbr: ['Monaco', 'Mônaco'] },
            { name: 'Vaticano', flag: '🇻🇦', capital: 'Vaticano', abbr: ['Vaticano', 'Vatican', 'Holy See'] },
            { name: 'Catar', flag: '🇶🇦', capital: 'Doha', abbr: ['Qatar', 'Catar'] },
            { name: 'Bahrein', flag: '🇧🇭', capital: 'Manama', abbr: ['Bahrein', 'Bahrain'] },
            { name: 'Kuwait', flag: '🇰🇼', capital: 'Kuwait City', abbr: ['Kuwait'] },
            { name: 'Omã', flag: '🇴🇲', capital: 'Mascate', abbr: ['Oma', 'Omã', 'Oman'] },
            { name: 'Iêmen', flag: '🇾🇪', capital: 'Sana\'a', abbr: ['Iemen', 'Iêmen', 'Yemen'] },
            { name: 'Coreia do Norte', flag: '🇰🇵', capital: 'Pyongyang', abbr: ['Coreia do Norte', 'North Korea'] },
            { name: 'Butão', flag: '🇧🇹', capital: 'Thimphu', abbr: ['Bhutan', 'Butão'] },
            { name: 'Caribe Holandês', flag: '🇧🇶', capital: 'Kralendijk', abbr: ['Caribe Holandes', 'Caribbean Netherlands'] },
            { name: 'Wallis e Futuna', flag: '🇼🇫', capital: 'Mata-Utu', abbr: ['Wallis e Futuna'] },
            { name: 'Maiote', flag: '🇾🇹', capital: 'Mamoudzou', abbr: ['Maiote', 'Mayotte'] },
            { name: 'Reunião', flag: '🇷🇪', capital: 'Saint-Denis', abbr: ['Reuniao', 'Reunião', 'Reunion'] },
        ]
    },

    // BRAZILIAN STATES
    brazilStates: {
        easy: [
            { name: 'São Paulo', abbr: ['SP', 'Sao Paulo'] },
            { name: 'Rio de Janeiro', abbr: ['RJ'] },
            { name: 'Minas Gerais', abbr: ['MG'] },
            { name: 'Bahia', abbr: ['BA'] },
            { name: 'Santa Catarina', abbr: ['SC'] },
            { name: 'Rio Grande do Sul', abbr: ['RS'] },
            { name: 'Paraná', abbr: ['PR', 'Parana'] },
            { name: 'Espírito Santo', abbr: ['ES'] },
            { name: 'Pernambuco', abbr: ['PE'] },
            { name: 'Ceará', abbr: ['CE', 'Ceara'] },
            { name: 'Goiás', abbr: ['GO', 'Goias'] },
            { name: 'Brasília', abbr: ['DF', 'Brasilia'] },
            { name: 'Maranhão', abbr: ['MA', 'Maranhao'] },
            { name: 'Piauí', abbr: ['PI', 'Piaui'] },
            { name: 'Rondônia', abbr: ['RO', 'Rondonia'] },
            { name: 'Amazonas', abbr: ['AM'] },
            { name: 'Roraima', abbr: ['RR'] },
            { name: 'Amapá', abbr: ['AP', 'Amapa'] },
            { name: 'Acre', abbr: ['AC'] },
            { name: 'Tocantins', abbr: ['TO'] },
            { name: 'Mato Grosso', abbr: ['MT'] },
            { name: 'Mato Grosso do Sul', abbr: ['MS'] },
            { name: 'Paraíba', abbr: ['PB', 'Paraiba'] },
            { name: 'Rio Grande do Norte', abbr: ['RN'] },
            { name: 'Alagoas', abbr: ['AL'] },
            { name: 'Sergipe', abbr: ['SE'] },
        ]
    },

    // BRAZILIAN CAPITALS
    brazilCapitals: [
        { state: 'São Paulo', city: 'São Paulo', abbr: ['Sao Paulo', 'São Paulo'] },
        { state: 'Rio de Janeiro', city: 'Rio de Janeiro', abbr: ['Rio', 'Rio de Janeiro'] },
        { state: 'Minas Gerais', city: 'Belo Horizonte', abbr: ['Belo Horizonte', 'BH'] },
        { state: 'Bahia', city: 'Salvador', abbr: ['Salvador'] },
        { state: 'Santa Catarina', city: 'Florianópolis', abbr: ['Florianopolis', 'Florianópolis'] },
        { state: 'Rio Grande do Sul', city: 'Porto Alegre', abbr: ['Porto Alegre', 'PA'] },
        { state: 'Paraná', city: 'Curitiba', abbr: ['Curitiba'] },
        { state: 'Espírito Santo', city: 'Vitória', abbr: ['Vitoria', 'Vitória'] },
        { state: 'Pernambuco', city: 'Recife', abbr: ['Recife'] },
        { state: 'Ceará', city: 'Fortaleza', abbr: ['Fortaleza'] },
        { state: 'Goiás', city: 'Goiânia', abbr: ['Goiania', 'Goiânia'] },
        { state: 'Brasília', city: 'Brasília', abbr: ['Brasilia', 'Brasília'] },
        { state: 'Maranhão', city: 'São Luís', abbr: ['Sao Luis', 'São Luís'] },
        { state: 'Piauí', city: 'Teresina', abbr: ['Teresina'] },
        { state: 'Rondônia', city: 'Porto Velho', abbr: ['Porto Velho'] },
        { state: 'Amazonas', city: 'Manaus', abbr: ['Manaus'] },
        { state: 'Roraima', city: 'Boa Vista', abbr: ['Boa Vista'] },
        { state: 'Amapá', city: 'Macapá', abbr: ['Macapa', 'Macapá'] },
        { state: 'Acre', city: 'Rio Branco', abbr: ['Rio Branco'] },
        { state: 'Tocantins', city: 'Palmas', abbr: ['Palmas'] },
        { state: 'Mato Grosso', city: 'Cuiabá', abbr: ['Cuiaba', 'Cuiabá'] },
        { state: 'Mato Grosso do Sul', city: 'Campo Grande', abbr: ['Campo Grande'] },
        { state: 'Paraíba', city: 'João Pessoa', abbr: ['Joao Pessoa', 'João Pessoa'] },
        { state: 'Rio Grande do Norte', city: 'Natal', abbr: ['Natal'] },
        { state: 'Alagoas', city: 'Maceió', abbr: ['Maceio', 'Maceió'] },
        { state: 'Sergipe', city: 'Aracaju', abbr: ['Aracaju'] },
    ],

    // COUNTRIES BY LANGUAGE
    languageCountries: {
        portuguese: ['Portugal', 'Brasil', 'Angola', 'Moçambique', 'Timor-Leste', 'Cabo Verde', 'Guiné-Bissau'],
        spanish: ['Espanha', 'México', 'Argentina', 'Colômbia', 'Peru', 'Venezuela', 'Chile', 'Equador', 'Bolívia', 'Paraguai', 'Uruguai', 'Guatemala', 'Honduras', 'El Salvador', 'Nicarágua', 'Costa Rica', 'Panamá', 'Cuba', 'República Dominicana', 'Porto Rico'],
        french: ['França', 'Bélgica', 'Suíça', 'Luxemburgo', 'Canadá', 'Haiti', 'Benin', 'Togo', 'Senegal', 'Mali', 'Burkina Fasso', 'Costa do Marfim'],
        english: ['Estados Unidos', 'Reino Unido', 'Irlanda', 'Austrália', 'Canadá', 'Índia', 'Paquistão', 'Bangladesh', 'Nigéria', 'Gana', 'Malta', 'Singapura', 'Malásia', 'Brunei', 'Fiji'],
        german: ['Alemanha', 'Áustria', 'Suíça', 'Luxemburgo', 'Liechtenstein', 'Bélgica']
    },

    // COUNTRIES BY STARTING LETTER
    countryStartsWith: {
        a: ['Afeganistão', 'Albânia', 'Alemanha', 'Andorra', 'Angola', 'Antígua e Barbuda', 'Arábia Saudita', 'Argentina', 'Armênia', 'Austrália', 'Áustria', 'Azerbaijão'],
        b: ['Bahamas', 'Bahrein', 'Bangladesh', 'Barbados', 'Bélgica', 'Belize', 'Benin', 'Bielorrússia', 'Bósnia e Herzegovina', 'Botswana', 'Brasil', 'Brunei', 'Bulgária'],
        c: ['Canadá', 'Catar', 'Cazaquistão', 'Chile', 'China', 'Chipre', 'Colômbia', 'Comores', 'Coreia do Sul', 'Costa Rica', 'Croácia', 'Cuba'],
        g: ['Gana', 'Geórgia', 'Grécia', 'Groenlândia', 'Guatemala', 'Guiana'],
        l: ['Laos', 'Lesoto', 'Letônia', 'Líbano', 'Libéria', 'Liechtenstein', 'Lituânia', 'Luxemburgo'],
        m: ['Malásia', 'Maldivas', 'Mali', 'Malta', 'Marrocos', 'Maurício', 'Moldávia', 'Mônaco', 'Mongólia', 'Montenegro', 'México'],
        p: ['Panamá', 'Papua Nova Guiné', 'Paquistão', 'Paraguai', 'Peru', 'Polônia', 'Portugal'],
        r: ['República Checa', 'República Dominicana', 'Romênia', 'Reino Unido', 'Rússia'],
        s: ['San Marino', 'Senegal', 'Servia', 'Singapura', 'Síria', 'Sri Lanka'],
        t: ['Tailândia', 'Tanzânia', 'Tajiquistão', 'Timor-Leste', 'Togo', 'Trinidad e Tobago', 'Turquia'],
        v: ['Vanuatu', 'Vaticano', 'Venezuela', 'Vietnã']
    },

    // WORLD BORDERS DATA
    worldBorders: {
        'Brasil': ['Uruguai', 'Argentina', 'Paraguai', 'Bolívia', 'Peru', 'Colômbia', 'Venezuela', 'Guiana', 'Surinã'],
        'Argentina': ['Brasil', 'Uruguai', 'Paraguai', 'Bolívia', 'Chile'],
        'China': ['Vietnã', 'Laos', 'Mianmar', 'Índia', 'Butão', 'Nepal', 'Paquistão', 'Afeganistão', 'Tajiquistão', 'Cazaquistão', 'Rússia', 'Mongólia', 'Coreia do Norte'],
        'Estados Unidos': ['Canadá', 'México'],
        'Canadá': ['Estados Unidos'],
        'México': ['Estados Unidos', 'Belize', 'Guatemala'],
        'Austrália': [],
        'Japão': [],
    },

    // COLLECTIONS FOR JETPUNK
    europeanCountries: [
        'Albânia', 'Andorra', 'Áustria', 'Bélgica', 'Bielorrússia', 'Bósnia e Herzegovina',
        'Bulgária', 'Croácia', 'Dinamarca', 'Eslováquia', 'Eslovênia', 'Espanha', 'Estônia',
        'Finlândia', 'França', 'Geórgia', 'Grécia', 'Hungria', 'Irlanda', 'Islândia', 'Itália',
        'Kosovo', 'Letônia', 'Liechtenstein', 'Lituânia', 'Luxemburgo', 'Macedônia do Norte',
        'Malta', 'Moldávia', 'Mônaco', 'Montenegro', 'Noruega', 'Países Baixos', 'Polônia',
        'Portugal', 'República Checa', 'Romênia', 'Reino Unido', 'Rússia', 'San Marino',
        'Servia', 'Suécia', 'Suíça', 'Ucrânia', 'Vaticano'
    ],

    // PI DIGITS
    piDigits: [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 8, 9, 7, 9]
};

// Load stats from localStorage
function loadStats() {
    const saved = localStorage.getItem('geographyGameStats');
    if (saved) {
        return JSON.parse(saved);
    }
    return {
        coins: 0,
        games: {},
        skins: { default: true },
        backgrounds: { default: true },
        equippedSkin: 'default',
        equippedBackground: 'default'
    };
}

// Save stats to localStorage
function saveStats(stats) {
    localStorage.setItem('geographyGameStats', JSON.stringify(stats));
}
